-- Run this once in the Supabase SQL Editor to set up the conversations table.

CREATE TABLE IF NOT EXISTS conversations (
    id               UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
    session_id       TEXT        NOT NULL,
    user_input       TEXT        NOT NULL,
    transcript       TEXT,                    -- verbatim speech-to-text (voice input only)
    emotion          TEXT,
    casel_competency TEXT,
    gemini_response  TEXT,
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

-- Week 2 migration: add transcript column if table already exists
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS transcript TEXT;

-- Week 3 migration: add sentiment and keyword extraction columns
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS sentiment TEXT;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS sentiment_score FLOAT;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS keywords TEXT;  -- JSON array of key phrases

-- Week 4 migration: pgvector embeddings and semantic retrieval

-- Enable the pgvector extension (safe to run multiple times)
CREATE EXTENSION IF NOT EXISTS vector;

-- Add 768-dimension embedding column (text-embedding-004 output size)
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS embedding vector(768);

-- IVFFlat index for fast approximate cosine-similarity search
-- Run this after at least a handful of rows exist for best results
CREATE INDEX IF NOT EXISTS conversations_embedding_idx
  ON conversations
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);

-- RPC function used by search_similar() in supabase_client.py
-- Returns rows ordered by cosine distance (0.0 = identical, 2.0 = opposite)
CREATE OR REPLACE FUNCTION match_conversations(
  query_embedding   vector(768),
  match_session_id  text,
  match_count       int DEFAULT 5
)
RETURNS TABLE (
  id                uuid,
  session_id        text,
  user_input        text,
  transcript        text,
  emotion           text,
  casel_competency  text,
  gemini_response   text,
  sentiment         text,
  sentiment_score   float,
  keywords          text,
  created_at        timestamptz,
  cosine_distance   float
)
LANGUAGE sql STABLE AS $$
  SELECT
    id, session_id, user_input, transcript, emotion, casel_competency,
    gemini_response, sentiment, sentiment_score, keywords, created_at,
    (embedding <=> query_embedding) AS cosine_distance
  FROM conversations
  WHERE session_id = match_session_id
    AND embedding IS NOT NULL
  ORDER BY embedding <=> query_embedding
  LIMIT match_count;
$$;

-- Week 5 migration: drift scoring and RAG contextualised response
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS drift_score FLOAT;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS context_response TEXT;

-- Week 6 migration: safeguarding flag agent and teacher dashboard

-- Flag column on conversations so each entry records whether it triggered an alert
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS flag_triggered BOOLEAN DEFAULT FALSE;

-- Safeguarding alerts table: one row per triggered flag event
CREATE TABLE IF NOT EXISTS safeguarding_alerts (
    id               UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
    session_id       TEXT        NOT NULL,
    conversation_id  UUID        REFERENCES conversations(id) ON DELETE SET NULL,
    severity         TEXT        NOT NULL CHECK (severity IN ('low', 'medium', 'high')),
    reason           TEXT        NOT NULL,
    triggered_at     TIMESTAMPTZ DEFAULT NOW(),
    acknowledged_at  TIMESTAMPTZ,
    teacher_notes    TEXT
);

-- Fast lookup of unacknowledged alerts (teacher dashboard active-alerts view)
CREATE INDEX IF NOT EXISTS safeguarding_alerts_unacked_idx
    ON safeguarding_alerts (acknowledged_at)
    WHERE acknowledged_at IS NULL;

-- Per-session alert history ordered by most recent
CREATE INDEX IF NOT EXISTS safeguarding_alerts_session_idx
    ON safeguarding_alerts (session_id, triggered_at DESC);

-- Week 7 migration: weekly session summary reports generated by Summariser Agent

CREATE TABLE IF NOT EXISTS session_summaries (
    id           UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
    session_id   TEXT        NOT NULL,
    period_start DATE        NOT NULL,
    period_end   DATE        NOT NULL,
    summary_text TEXT        NOT NULL,   -- full Gemini JSON response
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS session_summaries_session_idx
    ON session_summaries (session_id, created_at DESC);
